/**
 * Pack Verification Service - Usage Examples
 *
 * This file demonstrates how to use the Pack Verification Service
 * in various scenarios throughout the application.
 */

import { packVerificationService } from './pack-verification-service';
import { supabaseAdmin } from '@/lib/supabase/server';
import { readFileSync } from 'fs';

// ============================================================================
// EXAMPLE 1: Generate Verification Data for New Pack
// ============================================================================

/**
 * After generating a PDF pack, create verification data
 * This should be called in the pack generation job
 */
async function generatePackVerificationExample(
  packId: string,
  packFilePath: string
) {
  try {
    // Read the generated PDF file
    const packBuffer = readFileSync(packFilePath);

    // Create verification data (generates hash, stores it, and returns QR code)
    const verificationData = await packVerificationService.createVerification(
      packId,
      packBuffer
    );

    if (verificationData) {
      console.log('Verification data generated successfully:');
      console.log('- Pack ID:', verificationData.packId);
      console.log('- Content Hash:', verificationData.contentHash);
      console.log('- Verification URL:', verificationData.verificationUrl);
      console.log('- QR Code:', verificationData.qrCodeDataUrl.substring(0, 50) + '...');

      // You can now:
      // 1. Include the QR code in the PDF footer/header
      // 2. Email the verification URL to recipients
      // 3. Store the QR code for later display
      return verificationData;
    }
  } catch (error) {
    console.error('Failed to generate verification:', error);
    throw error;
  }
}

// ============================================================================
// EXAMPLE 2: Manual Hash Generation and Storage
// ============================================================================

/**
 * Manually generate and store verification hash
 * Useful if you want more control over the process
 */
async function manualVerificationSetupExample(
  packId: string,
  packBuffer: Buffer
) {
  try {
    // Step 1: Generate content hash
    const contentHash = packVerificationService.generateContentHash(packBuffer);
    console.log('Generated hash:', contentHash);

    // Step 2: Store the hash
    await packVerificationService.storeVerification(packId, contentHash);
    console.log('Hash stored successfully');

    // Step 3: Generate QR code separately
    const qrCode = await packVerificationService.generateQRCode(packId);
    console.log('QR code generated');

    return { contentHash, qrCode };
  } catch (error) {
    console.error('Manual verification setup failed:', error);
    throw error;
  }
}

// ============================================================================
// EXAMPLE 3: Verify Pack Authenticity (Public Endpoint)
// ============================================================================

/**
 * Verify a pack's authenticity
 * This is used by the public verification endpoint
 */
async function verifyPackExample(packId: string, providedHash?: string) {
  try {
    // Verify the pack
    const result = await packVerificationService.verifyPack(packId, providedHash);

    if (result.verified) {
      console.log('✓ Pack is authentic!');
      console.log('  Company:', result.companyName);
      console.log('  Site:', result.siteName);
      console.log('  Generated:', result.generatedAt);
      console.log('  Type:', result.packType);
    } else {
      console.log('✗ Pack verification failed');
      console.log('  Reason:', result.reason);
    }

    return result;
  } catch (error) {
    console.error('Verification error:', error);
    throw error;
  }
}

// ============================================================================
// EXAMPLE 4: Get Full Verification Data
// ============================================================================

/**
 * Retrieve complete verification data for a pack
 * Useful for displaying verification info in the UI
 */
async function getVerificationInfoExample(packId: string) {
  try {
    const data = await packVerificationService.getVerificationData(packId);

    if (data) {
      console.log('Pack Verification Information:');
      console.log('━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━');
      console.log('Pack ID:', data.packId);
      console.log('Company:', data.companyName);
      console.log('Site:', data.siteName);
      console.log('Pack Type:', data.packType);
      console.log('Generated:', data.generatedAt);
      console.log('Generated By:', data.generatedBy);
      console.log('Content Hash:', data.contentHash);
      console.log('Verification URL:', data.verificationUrl);
      console.log('QR Code available:', data.qrCodeDataUrl ? 'Yes' : 'No');
      console.log('━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━');

      return data;
    } else {
      console.log('Pack not found or not verified');
      return null;
    }
  } catch (error) {
    console.error('Failed to get verification data:', error);
    throw error;
  }
}

// ============================================================================
// EXAMPLE 5: Integration with Pack Generation Job
// ============================================================================

/**
 * How to integrate with the pack generation job
 * Add this to lib/jobs/pack-generation-job.ts
 */
async function packGenerationJobIntegrationExample(
  packId: string,
  pdfFilePath: string
) {
  try {
    console.log('Generating pack PDF...');
    // ... existing pack generation code ...

    console.log('PDF generated successfully, creating verification...');

    // Read the generated PDF
    const packBuffer = readFileSync(pdfFilePath);

    // Generate verification data
    const verification = await packVerificationService.createVerification(
      packId,
      packBuffer
    );

    if (verification) {
      console.log('Verification created:', verification.contentHash);

      // Optional: Update pack record with verification URL
      await supabaseAdmin
        .from('audit_packs')
        .update({
          metadata: {
            verification_url: verification.verificationUrl,
            qr_code_available: true,
          },
        })
        .eq('id', packId);

      return verification;
    }
  } catch (error) {
    console.error('Pack generation with verification failed:', error);
    throw error;
  }
}

// ============================================================================
// EXAMPLE 6: Add QR Code to PDF
// ============================================================================

/**
 * How to embed the QR code in a PDF
 * This can be added to the PDF generation logic
 */
async function addQRCodeToPDFExample(packId: string) {
  try {
    // Generate QR code
    const qrCodeDataUrl = await packVerificationService.generateQRCode(packId);

    // The QR code is a base64 data URL
    // Extract the base64 data
    const base64Data = qrCodeDataUrl.split(',')[1];
    const qrBuffer = Buffer.from(base64Data, 'base64');

    // You can now:
    // 1. Embed in PDF using pdf-lib or pdfkit
    // 2. Add to PDF footer with verification text
    // 3. Include on a separate verification page

    console.log('QR code ready for embedding');
    return qrBuffer;
  } catch (error) {
    console.error('Failed to prepare QR code:', error);
    throw error;
  }
}

// ============================================================================
// EXAMPLE 7: Verify Pack with Content Hash Check
// ============================================================================

/**
 * Verify a pack by checking both existence and content hash
 * Most secure verification method
 */
async function verifyWithHashExample(packId: string, uploadedFile: Buffer) {
  try {
    // Generate hash from uploaded file
    const uploadedHash = packVerificationService.generateContentHash(uploadedFile);

    // Verify against stored hash
    const result = await packVerificationService.verifyPack(packId, uploadedHash);

    if (result.verified) {
      console.log('✓ File is authentic and matches original pack');
      return { authentic: true, tamperedWith: false };
    } else {
      if (result.reason?.includes('hash mismatch')) {
        console.log('✗ File has been tampered with');
        return { authentic: false, tamperedWith: true };
      } else {
        console.log('✗ Verification failed:', result.reason);
        return { authentic: false, tamperedWith: false };
      }
    }
  } catch (error) {
    console.error('Hash verification failed:', error);
    throw error;
  }
}

// ============================================================================
// EXAMPLE 8: Public Verification Page
// ============================================================================

/**
 * How to use in a public verification page
 * This would be in a Next.js page or API route
 */
async function publicVerificationPageExample(packId: string) {
  try {
    // Call the verification API
    const response = await fetch(`/api/v1/packs/${packId}/verify`);
    const data = await response.json();

    if (data.data.verified) {
      // Display success message
      return {
        status: 'verified',
        message: 'This pack is authentic',
        details: {
          company: data.data.company_name,
          site: data.data.site_name,
          generatedAt: data.data.generated_at,
          packType: data.data.pack_type,
        },
      };
    } else {
      // Display failure message
      return {
        status: 'failed',
        message: 'Verification failed',
        reason: data.data.reason,
      };
    }
  } catch (error) {
    console.error('Verification page error:', error);
    return {
      status: 'error',
      message: 'Unable to verify pack',
    };
  }
}

// ============================================================================
// EXAMPLE 9: Email with QR Code
// ============================================================================

/**
 * Include QR code in email distribution
 */
async function emailWithQRCodeExample(packId: string, recipientEmail: string) {
  try {
    // Get verification data
    const verification = await packVerificationService.getVerificationData(packId);

    if (!verification) {
      throw new Error('Verification data not available');
    }

    // Prepare email content
    const emailBody = `
      <h2>Audit Pack Available</h2>
      <p>Your audit pack is ready for review.</p>

      <h3>Verification</h3>
      <p>This pack includes tamper-detection for authenticity.</p>
      <p>Scan the QR code below to verify:</p>

      <img src="${verification.qrCodeDataUrl}" alt="Verification QR Code" width="200" />

      <p>Or visit: <a href="${verification.verificationUrl}">${verification.verificationUrl}</a></p>

      <hr>
      <small>
        Pack ID: ${verification.packId}<br>
        Generated: ${verification.generatedAt}<br>
        Hash: ${verification.contentHash.substring(0, 16)}...
      </small>
    `;

    // Send email using your email service
    console.log('Email prepared with QR code for:', recipientEmail);
    return emailBody;
  } catch (error) {
    console.error('Failed to prepare email with QR code:', error);
    throw error;
  }
}

// ============================================================================
// EXPORTS
// ============================================================================

export {
  generatePackVerificationExample,
  manualVerificationSetupExample,
  verifyPackExample,
  getVerificationInfoExample,
  packGenerationJobIntegrationExample,
  addQRCodeToPDFExample,
  verifyWithHashExample,
  publicVerificationPageExample,
  emailWithQRCodeExample,
};
