-- Migration: Add cost tracking columns to extraction_logs
-- Reference: docs/specs/81_AI_Cost_Optimization.md Section 6.1

-- Add cost tracking columns
ALTER TABLE extraction_logs 
  ADD COLUMN IF NOT EXISTS input_tokens INTEGER NOT NULL DEFAULT 0,
  ADD COLUMN IF NOT EXISTS output_tokens INTEGER NOT NULL DEFAULT 0,
  ADD COLUMN IF NOT EXISTS estimated_cost DECIMAL(10, 6) NOT NULL DEFAULT 0,
  ADD COLUMN IF NOT EXISTS rule_library_hits INTEGER NOT NULL DEFAULT 0,
  ADD COLUMN IF NOT EXISTS api_calls_made INTEGER NOT NULL DEFAULT 0;

-- Add indexes for cost analytics
CREATE INDEX IF NOT EXISTS idx_extraction_logs_estimated_cost ON extraction_logs(estimated_cost);
-- Index on created_at for monthly analytics queries (filter at query time)
CREATE INDEX IF NOT EXISTS idx_extraction_logs_created_at ON extraction_logs(created_at);
CREATE INDEX IF NOT EXISTS idx_extraction_logs_rule_library_hits ON extraction_logs(rule_library_hits);

-- Migrate existing data from metadata JSONB to dedicated columns
UPDATE extraction_logs
SET 
  input_tokens = COALESCE((metadata->>'input_tokens')::INTEGER, 0),
  output_tokens = COALESCE((metadata->>'output_tokens')::INTEGER, 0),
  estimated_cost = COALESCE((metadata->>'estimated_cost')::DECIMAL, 0),
  rule_library_hits = CASE 
    WHEN (metadata->>'rule_library_hit')::BOOLEAN = true THEN 1 
    ELSE 0 
  END,
  api_calls_made = CASE 
    WHEN model_identifier != 'rule_library' THEN 1 
    ELSE 0 
  END
WHERE metadata IS NOT NULL;

COMMENT ON COLUMN extraction_logs.input_tokens IS 'Input tokens used in API call (0 if rule library match)';
COMMENT ON COLUMN extraction_logs.output_tokens IS 'Output tokens generated by API call (0 if rule library match)';
COMMENT ON COLUMN extraction_logs.estimated_cost IS 'Estimated cost in USD for this extraction';
COMMENT ON COLUMN extraction_logs.rule_library_hits IS 'Number of segments matched by rule library (cost savings)';
COMMENT ON COLUMN extraction_logs.api_calls_made IS 'Number of API calls made to LLM (0 if rule library match)';

